START   
**********************************************************************
* MAJOR ADDRESSING METHODS

* 1- Immediate Addressing
       LDA  A, $37
       LDA  B, $41
       LDA  CD, $3576                                                
       LDA  SK, $2000                                                

**********************************************************************
* 2- Implied (Register) Addressing
       MOV  A,B
       MOV  B,DK
       MOV  SK,YG

       EXC  A,C
       CHN  A

       CLR  A
       LSR  B
**********************************************************************
* 3- Direct Addressing
       STA  $95, $1250
       LDA  A,  <$1250>

**********************************************************************
* 4- Indirect Addressing
        STA  $45, $3010
        STA  $30, $2500
        STA  $10, $2501
        LDA  CD, <$2500>
        LDA  A, <CD>

*        LDA  A,(($2500))           
* --> Unresolved symbol hatasý! (Hatalý syntax)

**********************************************************************
* 5- Indexed Addressing
        STA  $75, $1025
        LDA SK, $1000
        LDA  A,  <SK+$25>


        STA  $85, $3500
        LDA  CD, $2500
        LDA  SK, $1000
        LDA  A, <SK+CD+0>

**********************************************************************
* 6- Relative Addressing
        CLR  A  

*        BRA $04
* Koþulsuz branch (4 byte ötedeki adrese git).
* --> Fakat PS=$0004 olan adrese gidiyor!                     

        BRA  ILERI

        INC A
        INC A
ILERI   INC A

*#######################################################################
*#######################################################################

* ADVANCED ADDRESSING METHODS

**********************************************************************
* 1- Memory Immediate Write
         STA  $37, $1250 

**********************************************************************
* 2- Incremented Index Addressing 
         STA  $90, $1025
         LDA  SK, $1000
         LDA  A, <SK+$25> + $10

**********************************************************************
* 3- Decremented Index Addressing
         STA  $80, $1015
         LDA  SK, $1000
         LDA  A, <SK+$25> - $10

**********************************************************************
* 4- Register Relative Index Addressing 
        STA  $70, $120A
        LDA  SK, $1000
        LDA  CD, $0205
        LDA  A, <CD+SK+$05>

**********************************************************************
END

