ORG $C000
	LDA B,%11111111
	RTI

ORG $0000
START	LDA   YG,$2000
	LDA   SK,$1000
	LDA   B, 10	; Loop counter
	STA $C0, <$FFF8>	
	STA $00, <$FFF9>	
	LDA A,%00001010
	STA A,<DURDEN.A>
	LDA A,DURDEN.A
WAIT	BRA WAIT

