START	LDA YG, $FFFF
	LDA AB, $1000
	PSH B
	PSH A
	BSR SQRT
	STA C, <$1002>
	INT

SQRT	PSH B
	PSH A
	MOV AB,SK
	PSH B
	PSH A
	LDA SK, <YG+07>
	CLR C
	LDA B, <SK+00>
	INC B
	ROR B
CONT1	SUB B,C
	BGT CONT2
	PUL A
	PUL B
	MOV SK, AB
	PUL A
	PUL B
	RTS
CONT2	INC C
	BRA CONT1
