# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "trusty32"
    config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-i386-vagrant-disk1.box"

    config.vm.network :forwarded_port, guest: 50000, host: 50000
    config.vm.network :forwarded_port, guest: 5000, host: 5050

    config.vm.provider "virtualbox" do |vb|
        # vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--name", "itucsdb" ]
    end

    # fix locale
    config.vm.provision :shell do |shell|
        shell.path = "fixlocale.sh"
    end

    # Run apt-get update as a separate step in order to avoid
    # package install errors
    config.vm.provision :puppet do |puppet|
        puppet.manifests_path = "."
        puppet.manifest_file  = "aptgetupdate.pp"
    end

    # ensure we have the packages we need
    config.vm.provision :puppet do |puppet|
        puppet.manifests_path = "."
        puppet.manifest_file  = "itucsdb2.pp"
    end

    # install IBM DB2
    config.vm.provision :shell do |shell|
        shell.path = "installdb2.sh"
    end
end
