
START STA $00,YÖNLEN.A
	STA $FF,YÖNLEN.B
	LDA C,$80
LOOP	LDA A,<ÝSKELE.A>
	AND A,$80
	CMP A,$80
	BEQ FLA

*walking led
WAL	STA C,ÝSKELE.B
	LDA AB,$00
WA	ADD AB,$1
	CMP AB,$9FFF
	BNE WA
	LSR C
	CMP C,$00
	BNE LOOP
	LDA C,$80
	JMP LOOP

*flashing led
FLA	LDA D,$00
	STA D,ÝSKELE.B
	LDA AB,$00
WB	ADD AB,$1
	CMP AB,$9FFF
	BNE WB
	LDA D,$FF
	STA D,ÝSKELE.B
WC	ADD AB,$1
	CMP AB,$9FFF
	BNE WC
	JMP LOOP
	INT