#ifndef __MESSAGEBOX_H
#define __MESSAGEBOX_H

#include <linux/ioctl.h>

#define MESSAGEBOX_IOC_MAGIC  'k'
#define MESSAGEBOX_EXCLUDE_READ _IO(MESSAGEBOX_IOC_MAGIC,  13)
#define MESSAGEBOX_INCLUDE_READ _IO(MESSAGEBOX_IOC_MAGIC,  14)
#define MESSAGEBOX_MAX_SIZE _IOWR(MESSAGEBOX_IOC_MAGIC,  15, int)
#define MESSAGEBOX_DELETE_MESAGE _IOWR(MESSAGEBOX_IOC_MAGIC,  16, char *)
#define MESSAGEBOX_IOC_MAXNR 16

#endif
