
* Student Number : 150150701
* Student Name : Yunus Güngör

START STA $00,YÖNLEN.A
	STA $FF,YÖNLEN.B
	LDA C,$80
LOOP	LDA A,<ÝSKELE.A>
	AND A,$80
*make d1-d7 zero to check d0
	CMP A,$80
*check d0 if zero or one
	BEQ FLED

*walking led
WLED	STA C,ÝSKELE.B
	BSR WAIT
	LSR C
	CMP C,$00
	BEQ RES
	JMP LOOP

*reset c register to 10000000
RES	LDA C,$80
	JMP LOOP

*flashing led
FLED	LDA D,$00
	STA D,ÝSKELE.B
	BSR WAIT
	LDA D,$FF
	STA D,ÝSKELE.B
	BSR WAIT
	JMP LOOP
	INT

WAIT LDA AB,$00
WL	ADD AB,$1
	CMP AB,$9FFF
	BNE WL
	RTS